 - name: Build Docker image from Dockerfile
   docker_image:
     name: nginx
     path: ../
     state: build
        
 - name: Running the container
   docker_container:
     image: nginx:latest
     path: ../
     state: running
