    # This playbook contains docker actions that will be run on "remote" host.
  - name: Install apt_key dependencies
    apt:
      name: '{{ item }}'
    with_items: [python-urllib3, python-openssl, python-pyasn1, python-pip]
    when: ansible_distribution == 'Ubuntu' or ansible_distribution_release == 'trusty'

  - name: Install apt_key dependencies
    command: pip install ndg-httpsclient
    when: ansible_distribution == 'Ubuntu' or ansible_distribution_release == 'trusty' 

  - name: Install prerequisites
    apt:     name={{item}} update_cache=yes
    with_items:
     - apt-transport-https
     - ca-certificates
     - curl
     - software-properties-common

  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

  - name: Install Docker
    apt: name=docker-ce 
